#!/bin/sh

execdir="$PWD"

# valgrind tests memory usage.
# wine allow for windows testing on linux
if [ -n "${PARVALGRINDOPTS+set}" ]
then
    PARBINARY="valgrind $PARVALGRINDOPTS $execdir/par2"
elif [ "`which wine`" != "" ] && [ -f "$execdir/par2.exe" ]
then
    PARBINARY="wine $execdir/par2.exe"
else
    PARBINARY="$execdir/par2"
fi


if [ -z "$srcdir" ] || [ "." = "$srcdir" ]; then
  srcdir="$PWD"
  TESTDATA="$srcdir/tests"
else
  srcdir="$PWD/$srcdir"
  TESTDATA="$srcdir/tests"
fi

TESTROOT="$PWD"

testname=$(basename $0)
rm -f "$testname.log"
rm -rf "run$testname"

mkdir "run$testname" && cd "run$testname" || { echo "ERROR: Could not change to test directory" ; exit 1; } >&2

tar -xzf "$TESTDATA/smallsubdirdata.tar.gz" || { echo "ERROR: Could not extract data test files" ; exit 1; } >&2

banner="Bug 150, Files in rootfolder are not used with recursion"
dashes=`echo "$banner" | sed s/./-/g`

echo $dashes
echo $banner
echo $dashes

# before the subdirs
echo "file in rootpath" > aaaa-test.data
# after the subdirs
echo "another file in rootpath" > test-a.data

######
# BEFORE:
#
# $ tree
# .
# ├── aaaa-test.data
# ├── subdir1
# │   └── test-0.data
# ├── subdir2
# │   ├── test-1.data
# │   ├── test-2.data
# │   ├── test-3.data
# │   ├── test-4.data
# │   ├── test-5.data
# │   ├── test-6.data
# │   ├── test-7.data
# │   ├── test-8.data
# │   └── test-9.data
# └── test-a.data
# 
# 3 directories, 12 files
######

$PARBINARY create -R * || { echo "ERROR: Recursive creation of PAR 2.0 files failed" ; exit 1; } >&2

######
# AFTER:
#
# tree 
# .
# ├── aaaa-test.data
# ├── aaaa-test.data.par2
# ├── aaaa-test.data.vol000+01.par2
# ├── aaaa-test.data.vol001+02.par2
# ├── aaaa-test.data.vol003+04.par2
# ├── aaaa-test.data.vol007+08.par2
# ├── aaaa-test.data.vol015+16.par2
# ├── aaaa-test.data.vol031+32.par2
# ├── aaaa-test.data.vol063+37.par2
# ├── subdir1
# │   └── test-0.data
# ├── subdir2
# │   ├── test-1.data
# │   ├── test-2.data
# │   ├── test-3.data
# │   ├── test-4.data
# │   ├── test-5.data
# │   ├── test-6.data
# │   ├── test-7.data
# │   ├── test-8.data
# │   └── test-9.data
# └── test-a.data
# 
# 3 directories, 20 files
######

# The first file in the wildcard expansion is used ad parfilename so not
# covered for repair
rm aaaa-test.data

$PARBINARY verify aaaa-test.data.par2 || { echo "ERROR: verify of rootpath inclusion failed" ; exit 1; } >&2

cd "$TESTROOT"
rm -rf "run$testname"

exit 0
